plugin:
    name: 'dojo.pos::lang.plugin.name'
    description: 'dojo.pos::lang.plugin.description'
    author: Dojo
    icon: oc-icon-book
    homepage: ''
permissions:
    access_products:
        tab: 'dojo.pos::lang.permission.access_products'
        label: 'dojo.pos::lang.permission.access_products'
navigation:
    products-menu-item:
        label: 'dojo.pos::lang.menu_item.products'
        url: dojo/pos/products
        icon: icon-bookmark
        permissions:
            - access_products
