plugin:
    name: 'dojo.pos::lang.plugin.name'
    description: 'dojo.pos::lang.plugin.description'
    author: Dojo
    icon: oc-icon-book
    homepage: ''
permissions:
    access_products:
        tab: 'dojo.pos::lang.permission.access_products'
        label: 'dojo.pos::lang.permission.access_products'
    access_product_categories:
        tab: 'dojo.pos::lang.permission.access_product_categories'
        label: 'dojo.pos::lang.permission.access_product_categories'
    access_inventory_data_trackings:
        tab: 'dojo.pos::lang.permission.access_inventory_data_trackings'
        label: 'dojo.pos::lang.permission.access_inventory_data_trackings'
navigation:
    products-menu-item:
        label: 'dojo.pos::lang.menu_item.products'
        url: dojo/pos/products
        icon: icon-bookmark
        permissions: {  }
        sideMenu:
            side-menu-item:
                label: 'dojo.pos::lang.menu_item.products'
                url: /
                icon: icon-sitemap
                permissions:
                    - access_products
            product-categories-menu-item:
                label: 'dojo.pos::lang.menu_item.product_categories'
                url: dojo/pos/productcategories
                icon: icon-simplybuilt
                permissions:
                    - access_product_categories
            inventory-data-trackings-menu-item:
                label: 'dojo.pos::lang.menu_item.inventory_data_trackings'
                url: dojo/pos/inventorydatatrackings
                icon: icon-sitemap
                permissions:
                    - access_inventory_data_trackings
