list: $/dojo/pos/models/productcategory/columns.yaml
modelClass: Dojo\Pos\Models\ProductCategory
title: ProductCategories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dojo/pos/productcategories/update/:id'
