name: 'dojo.pos::lang.menu_item.product_category'
modelClass: Dojo\Pos\Models\ProductCategory
form: $/dojo/pos/models/productcategory/fields.yaml
defaultRedirect: dojo/pos/productcategories
create:
    redirect: 'dojo/pos/productcategories/update/:id'
    redirectClose: dojo/pos/productcategories
update:
    redirect: dojo/pos/productcategories
    redirectClose: dojo/pos/productcategories
preview: {  }
