title: 'dojo.pos::lang.menu_item.product_categories'
modelClass: Dojo\Pos\Models\ProductCategory
list: $/dojo/pos/models/productcategory/columns.yaml
recordUrl: 'dojo/pos/productcategories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
