list: $/dojo/pos/models/inventorydatatracking/columns.yaml
modelClass: Dojo\Pos\Models\InventoryDataTracking
title: InventoryDataTrackings
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dojo/pos/inventorydatatrackings/update/:id'
