title: 'dojo.pos::lang.menu_item.inventory_data_trackings'
modelClass: Dojo\Pos\Models\InventoryDataTracking
list: $/dojo/pos/models/inventorydatatracking/columns.yaml
recordUrl: 'dojo/pos/inventorydatatrackings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: false
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
